In [1]:
import pandas as pd
import numpy as np

from pandas import Series as s, DataFrame as df
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model, metrics 

In [2]:
breast_cancer = pd.read_csv('breast_cancer.csv')

In [3]:
breast_cancer.head()

Unnamed: 0  mean radius  mean texture  mean perimeter  mean area  \
0         0.0        17.99         10.38          122.80     1001.0   
1         1.0        20.57         17.77          132.90     1326.0   
2         2.0        19.69         21.25          130.00     1203.0   
3         3.0        11.42         20.38           77.58      386.1   
4         4.0        20.29         14.34          135.10     1297.0   

   mean smoothness  mean compactness  mean concavity  mean concave points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   mean symmetry   ...     worst texture  worst perimeter  worst area  \
0         0.2419   ...             17.33           184.60      2019.0   
1         0.1812   ...             23.41           158.80      1956.0   
2         0.2069   ...             25.53           152.50      1709.0   
3         0.2597   ...             26.50            98.87       567.7   
4         0.1809   ...             16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  outcome  
0          0.4601                  0.11890        0  
1          0.2750                  0.08902        0  
2          0.3613                  0.08758        0  
3          0.6638                  0.17300        0  
4          0.2364                  0.07678        0  

[5 rows x 32 columns]

In [4]:
breast_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 32 columns):
Unnamed: 0                 569 non-null float64
mean radius                569 non-null float64
mean texture               569 non-null float64
mean perimeter             569 non-null float64
mean area                  569 non-null float64
mean smoothness            569 non-null float64
mean compactness           569 non-null float64
mean concavity             569 non-null float64
mean concave points        569 non-null float64
mean symmetry              569 non-null float64
mean fractal dimension     569 non-null float64
radius error               569 non-null float64
texture error              569 non-null float64
perimeter error            569 non-null float64
area error                 569 non-null float64
smoothness error           569 non-null float64
compactness error          569 non-null float64
concavity error            569 non-null float64
concave points error       569 

In [5]:
breast_cancer.shape

(570, 32)

In [6]:
data = breast_cancer.loc[0: 568 , :] # or  breast_cancer.dropna(inplace = true)

In [7]:
data.tail(5)

Unnamed: 0  mean radius  mean texture  mean perimeter  mean area  \
564       564.0        21.56         22.39          142.00     1479.0   
565       565.0        20.13         28.25          131.20     1261.0   
566       566.0        16.60         28.08          108.30      858.1   
567       567.0        20.60         29.33          140.10     1265.0   
568       568.0         7.76         24.54           47.92      181.0   

     mean smoothness  mean compactness  mean concavity  mean concave points  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     mean symmetry   ...     worst texture  worst perimeter  worst area  \
564         0.1726   ...             26.40           166.10      2027.0   
565         0.1752   ...             38.25           155.00      1731.0   
566         0.1590   ...             34.12           126.70      1124.0   
567         0.2397   ...             39.42           184.60      1821.0   
568         0.1587   ...             30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  outcome  
564                0.2216          0.2060                  0.07115        0  
565                0.1628          0.2572                  0.06637        0  
566                0.1418          0.2218                  0.07820        0  
567                0.2650          0.4087                  0.12400        0  
568                0.0000          0.2871                  0.07039        1  

[5 rows x 32 columns]

In [8]:
data.shape

(569, 32)

In [9]:
#data["outcome"].dropna()

In [10]:
#data["mean radius"].dropna()

In [11]:
#data["mean concave points"].dropna()

In [12]:
#data["mean perimeter"].dropna()

In [13]:
data.columns

Index(['Unnamed: 0', 'mean radius', 'mean texture', 'mean perimeter',
       'mean area', 'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'outcome'],
      dtype='object')

In [97]:
# feature engineering
#x = data.iloc[:,1:-1]
x = data.loc[:,["mean radius","mean perimeter","mean smoothness"]]
y = data.outcome

In [98]:
x_train, x_test , y_train , y_test = train_test_split(x ,y , test_size = 0.3 , random_state = 10 )

In [99]:
model = linear_model.LogisticRegression()

In [100]:
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [101]:
predict_x = model.predict(x_test)
predict_x

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [145]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report , f1_score 

In [146]:
accuracy_score(y_test , predict_x)

0.9122807017543859

In [147]:
confusion_matrix(y_test , predict_x)

array([[ 46,  13],
       [  2, 110]])

In [148]:
from collections import Counter as c

In [149]:
c(y_test)

Counter({0: 59, 1: 112})

In [150]:
c(y_train)

Counter({1: 245, 0: 153})

In [151]:
print(classification_report)

<function classification_report at 0x108b14510>


In [152]:
print(classification_report(y_test , predict_x))

             precision    recall  f1-score   support

          0       0.96      0.78      0.86        59
          1       0.89      0.98      0.94       112

avg / total       0.92      0.91      0.91       171



In [153]:
print(f1_score(y_test , predict_x))

0.9361702127659575


In [154]:
from sklearn.preprocessing import scale , StandardScaler

In [155]:
x = scale(x)
x

array([[ 1.09706398,  1.26993369,  1.56846633],
       [ 1.82982061,  1.68595471, -0.82696245],
       [ 1.57988811,  1.56650313,  0.94221044],
       ...,
       [ 0.70228425,  0.67267578, -0.84048388],
       [ 1.83834103,  1.98252415,  1.52576706],
       [-1.80840125, -1.81438851, -3.11208479]])

In [156]:
x[1:5]

array([[ 1.82982061,  1.68595471, -0.82696245],
       [ 1.57988811,  1.56650313,  0.94221044],
       [-0.76890929, -0.59268717,  3.28355348],
       [ 1.75029663,  1.77657315,  0.28037183]])

In [157]:
# Scaling the data is 2 types 1) normalization and 2) Standard Dev
scaling = StandardScaler()
scaling.fit(x)
x = scaling.fit_transform(x)
# x_new= scaling.fit_transform(x_new)
# x = scale(x)

x

array([[ 1.09706398,  1.26993369,  1.56846633],
       [ 1.82982061,  1.68595471, -0.82696245],
       [ 1.57988811,  1.56650313,  0.94221044],
       ...,
       [ 0.70228425,  0.67267578, -0.84048388],
       [ 1.83834103,  1.98252415,  1.52576706],
       [-1.80840125, -1.81438851, -3.11208479]])