In [1]:
#numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)



'''
1	
object

Any object exposing the array interface method returns an array, or any (nested) sequence.

2	
dtype

Desired data type of array, optional

3	
copy

Optional. By default (true), the object is copied

4	
order

C (row major) or F (column major) or A (any) (default)

5	
subok

By default, returned array forced to be a base class array. If true, sub-classes passed through

6	
ndimin

Specifies minimum dimensions of resultant array
'''

'\n1\t\nobject\n\nAny object exposing the array interface method returns an array, or any (nested) sequence.\n\n2\t\ndtype\n\nDesired data type of array, optional\n\n3\t\ncopy\n\nOptional. By default (true), the object is copied\n\n4\t\norder\n\nC (row major) or F (column major) or A (any) (default)\n\n5\t\nsubok\n\nBy default, returned array forced to be a base class array. If true, sub-classes passed through\n\n6\t\nndimin\n\nSpecifies minimum dimensions of resultant array\n'

In [9]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


2 way to change the shape : 1) a.shape = (3,2) or 2) a = a.reshape(3,2)

In [10]:
# this resizes the ndarray 
a.shape = (3,2) 
print (a) 

[[1 2]
 [3 4]
 [5 6]]


In [12]:
b = a.reshape(3,2) 
print(a)
print("*"*50)
print (b)

[[1 2]
 [3 4]
 [5 6]]
**************************************************
[[1 2]
 [3 4]
 [5 6]]


In [28]:

# an array of evenly spaced numbers 
val = np.arange(2,24) 
print("val : ", val)
a = np.arange(24) 
print (a)
print (a.itemsize)

val :  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
4


In [29]:
# now reshape it 
b = a.reshape(2,4,3) 
print (b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [30]:
print (a.itemsize)

4


In [31]:
print (b.itemsize)

4


In [32]:
'''
numpy.empty(shape, dtype = float, order = 'C')
The constructor takes the following parameters.

Sr.No.	Parameter & Description
1	
Shape

Shape of an empty array in int or tuple of int

2	
Dtype

Desired output data type. Optional

3	
Order

'C' for C-style row-major array, 'F' for FORTRAN style column-major array
'''

"\nnumpy.empty(shape, dtype = float, order = 'C')\nThe constructor takes the following parameters.\n\nSr.No.\tParameter & Description\n1\t\nShape\n\nShape of an empty array in int or tuple of int\n\n2\t\nDtype\n\nDesired output data type. Optional\n\n3\t\nOrder\n\n'C' for C-style row-major array, 'F' for FORTRAN style column-major array\n"

In [34]:
# create list object using range function 
list1 = range(50) 
list2 = range(2,50) 
print (range(50))
print(list1)
print(list2)

range(0, 50)
range(0, 50)
range(2, 50)


In [57]:
list_age = [20,25,30,35]
age = np.array(list_age)
print(age)
print(type(age))
print(type(age[0]))


age.astype(float)

print("*"*50)
print(age)
print(type(age))
print(type(age[0]))

[20 25 30 35]
<class 'numpy.ndarray'>
<class 'numpy.int32'>
**************************************************
[20 25 30 35]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


# Change data types in dataframe and numpy

1)DF :

df["age"].astype(float)

2)Numpy: a = np.arrar(list_age)

a = a.astype(float)

In [58]:
# use iterator to create ndarray 
x = np.fromiter(list, dtype = float) 
print (x)

print("*"*80)
x1 = np.fromiter(list, dtype = int) 
print (x1)

print("*"*80)
print(type(x))
print(type(x1))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
********************************************************************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
********************************************************************************
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [59]:
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


In [60]:
y = np.arange(10,20,3) 
print(y)

[10 13 16 19]


In [61]:
xz = np.arange(10,20,4) 
print(xz)

[10 14 18]


In [62]:
x = np.arange(10,200,6) 
print(x)

[ 10  16  22  28  34  40  46  52  58  64  70  76  82  88  94 100 106 112
 118 124 130 136 142 148 154 160 166 172 178 184 190 196]


In [63]:
'''
numpy.linspace
This function is similar to arange() function. 
In this function, instead of step size, the number of evenly spaced values between the interval is specified. 
The usage of this function is as follows 

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

'''

'\nnumpy.linspace\nThis function is similar to arange() function. \nIn this function, instead of step size, the number of evenly spaced values between the interval is specified. \nThe usage of this function is as follows \n\nnumpy.linspace(start, stop, num, endpoint, retstep, dtype)\n\n'

In [64]:
'''
1	
start

The starting value of the sequence

2	
stop

The end value of the sequence, included in the sequence if endpoint set to true

3	
num

The number of evenly spaced samples to be generated. Default is 50

4	
endpoint

True by default, hence the stop value is included in the sequence. If false, it is not included

5	
retstep

If true, returns samples and step between the consecutive numbers

6	
dtype

Data type of output ndarray
'''

'\n1\t\nstart\n\nThe starting value of the sequence\n\n2\t\nstop\n\nThe end value of the sequence, included in the sequence if endpoint set to true\n\n3\t\nnum\n\nThe number of evenly spaced samples to be generated. Default is 50\n\n4\t\nendpoint\n\nTrue by default, hence the stop value is included in the sequence. If false, it is not included\n\n5\t\nretstep\n\nIf true, returns samples and step between the consecutive numbers\n\n6\t\ndtype\n\nData type of output ndarray\n'

In [65]:
x = np.linspace(10,20,5) 
print (x)


[10.  12.5 15.  17.5 20. ]


In [66]:
x = np.linspace(10,200,5) 
print (x)

[ 10.   57.5 105.  152.5 200. ]


In [67]:
x = np.linspace(10,200,10) 
print (x)

[ 10.          31.11111111  52.22222222  73.33333333  94.44444444
 115.55555556 136.66666667 157.77777778 178.88888889 200.        ]


In [68]:
x = np.linspace(0,200,10) 
print (x)

[  0.          22.22222222  44.44444444  66.66666667  88.88888889
 111.11111111 133.33333333 155.55555556 177.77777778 200.        ]


In [69]:
# endpoint set to false 
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [70]:
# endpoint set to false 
x = np.linspace(10,200, 5, endpoint = False) 
print (x)

[ 10.  48.  86. 124. 162.]


In [71]:
# endpoint set to false 
x = np.linspace(100,200, 5, endpoint = False) 
print (x)

[100. 120. 140. 160. 180.]


In [74]:
# find retstep value 


x = np.linspace(2,10,5, retstep = True) 
print (x) 
# retstep here is 0.25

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)


In [75]:
x = np.linspace(10,200,5, retstep = True) 
print (x) 
# retstep here is 0.25

(array([ 10. ,  57.5, 105. , 152.5, 200. ]), 47.5)


In [76]:
'''
numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. 
Start and stop endpoints of the scale are indices of the base, usually 10.
'''

'\nnumpy.logspace\nThis function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. \nStart and stop endpoints of the scale are indices of the base, usually 10.\n'

In [77]:
'''
1	
start

The starting point of the sequence is basestart

2	
stop

The final value of sequence is basestop

3	
num

The number of values between the range. Default is 50

4	
endpoint

If true, stop is the last value in the range

5	
base

Base of log space, default is 10

6	
dtype

Data type of output array. If not given, it depends upon other input arguments

'''

'\n1\t\nstart\n\nThe starting point of the sequence is basestart\n\n2\t\nstop\n\nThe final value of sequence is basestop\n\n3\t\nnum\n\nThe number of values between the range. Default is 50\n\n4\t\nendpoint\n\nIf true, stop is the last value in the range\n\n5\t\nbase\n\nBase of log space, default is 10\n\n6\t\ndtype\n\nData type of output array. If not given, it depends upon other input arguments\n\n'

In [78]:

# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [79]:
# default base is 10 
a = np.logspace(15.0, 2.0, num = 10) 
print (a)

[1.00000000e+15 3.59381366e+13 1.29154967e+12 4.64158883e+10
 1.66810054e+09 5.99484250e+07 2.15443469e+06 7.74263683e+04
 2.78255940e+03 1.00000000e+02]


In [80]:
# default base is 10 
a = np.logspace(15.0, 20.0, num = 10) 
print (a)

[1.00000000e+15 3.59381366e+15 1.29154967e+16 4.64158883e+16
 1.66810054e+17 5.99484250e+17 2.15443469e+18 7.74263683e+18
 2.78255940e+19 1.00000000e+20]


In [81]:
# set base of log space to 2 

a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [82]:
# set base of log space to 2 

a = np.logspace(10,100,num = 10, base = 2) 
print (a)

[1.02400000e+03 1.04857600e+06 1.07374182e+09 1.09951163e+12
 1.12589991e+15 1.15292150e+18 1.18059162e+21 1.20892582e+24
 1.23794004e+27 1.26765060e+30]


In [83]:
# set base of log space to 2 

a = np.logspace(1,10,num = 10, base = 4) 
print (a)

[4.000000e+00 1.600000e+01 6.400000e+01 2.560000e+02 1.024000e+03
 4.096000e+03 1.638400e+04 6.553600e+04 2.621440e+05 1.048576e+06]


In [84]:
# set base of log space to 2 

a = np.logspace(1,10,num = 10, base = 8) 
print (a)

[8.00000000e+00 6.40000000e+01 5.12000000e+02 4.09600000e+03
 3.27680000e+04 2.62144000e+05 2.09715200e+06 1.67772160e+07
 1.34217728e+08 1.07374182e+09]


In [85]:
'''
As mentioned earlier, items in ndarray object follows zero-based index.
Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. 
A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. 
This slice object is passed to the array to extract a part of array.
'''

"\nAs mentioned earlier, items in ndarray object follows zero-based index.\nThree types of indexing methods are available − field access, basic slicing and advanced indexing.\n\nBasic slicing is an extension of Python's basic concept of slicing to n dimensions. \nA Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. \nThis slice object is passed to the array to extract a part of array.\n"

In [90]:
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [91]:
## a = np.arange(100) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [92]:
a = np.arange(10) 
s = slice(2,50,4) 
print (a[s])

[2 6]


In [93]:
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [60]:
a = np.arange(100) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [63]:
a = np.arange(400) 
b = a[5] 
print (b)

5


In [65]:
a = np.arange(4000) 
b = a[50] 
print (b)

50


In [66]:
# slice items starting from index 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [67]:
# slice items starting from index 
a = np.arange(10) 
print (a[-2:])

[8 9]


In [68]:
# slice items starting from index 
a = np.arange(10) 
print (a[5:])

[5 6 7 8 9]


In [69]:
# slice items starting from index 
a = np.arange(10) 
print (a[:-2])

[0 1 2 3 4 5 6 7]


In [70]:
# slice items starting from index 
a = np.arange(10) 
print (a[-2:-1])

[8]


In [71]:
# slice items starting from index 
a = np.arange(10) 
print (a[-4:1])

[]


In [72]:
# slice items starting from index 
a = np.arange(10) 
print (a[-4:-1])

[6 7 8]


In [73]:
# slice items starting from index 
a = np.arange(10) 
print (a[-4:-2])

[6 7]


In [74]:
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [77]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [78]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[2:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[4 5 6]]


In [79]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[3:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[]


In [80]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[:1])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[1 2 3]]


In [81]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[:2])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[1 2 3]
 [3 4 5]]


In [82]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[:3])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [84]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)  
# this returns array of items in the second column 
print ('The items in the second column are:'  )
print (a[...,1] )
#print '\n'  

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...] )
#print '\n'  

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]
The items in the second row are:
[3 4 5]
The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [85]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [91]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a)
  
print ('Second array:') 
print (b) 
 
print ('First Array + Second Array' )
print (a + b)

First array:
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]
Second array:
[ 1.  2.  3.]
First Array + Second Array
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [92]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0],[4.0,6.0,8.0])  
   
print ('First array:') 
print (a)
  
print ('Second array:') 
print (b) 
 
print ('First Array + Second Array' )
print (a + b)

TypeError: data type not understood

In [94]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([4.0,6.0,8.0])  
   
print ('First array:') 
print (a)
  
print ('Second array:') 
print (b) 
 
print ('First Array + Second Array' )
print (a + b)

First array:
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]
Second array:
[ 4.  6.  8.]
First Array + Second Array
[[  4.   6.   8.]
 [ 14.  16.  18.]
 [ 24.  26.  28.]
 [ 34.  36.  38.]]


In [95]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([4.0,6.0,8.0])  
   
print ('First array:') 
print (a)
  
print ('Second array:') 
print (b) 
 
print ('First Array + Second Array' )
print (a * b)

First array:
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]
Second array:
[ 4.  6.  8.]
First Array + Second Array
[[   0.    0.    0.]
 [  40.   60.   80.]
 [  80.  120.  160.]
 [ 120.  180.  240.]]
